version: "3.1"

services:
  application:
    image: application
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - worker

  worker:
    image: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis

  flower:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  redis:
    image: redis
    ports:
      - 6379:6379
