# Generated by Django 4.0.6 on 2022-07-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MetricStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('median', models.FloatField()),
                ('percentile25', models.FloatField()),
                ('percentile75', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.day')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.location')),
                ('metrics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='summarizer.metrics')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='summarizer.day')),
                ('temp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='summarizer.metricstats')),
            ],
        ),
    ]
